import type { TodoWithFavorites } from '@/api/todos';

export const MOCK_FAVORITES: TodoWithFavorites[] = [
  {
    id: 1,
    teamId: 'team1',
    userId: 1,
    goalId: 10,
    title: '사용자 데이터 렌더링 구현',
    done: false,
    fileUrl: null,
    linkUrl: 'https://example.com',
    dueDate: '2025-04-10',
    createdAt: '2025-03-01',
    updatedAt: '2025-03-01',
    goal: { id: 10, title: '프론트엔드 개발' },
    noteIds: [1],
    tags: [],
    favorites: true,
  },
  {
    id: 2,
    teamId: 'team1',
    userId: 1,
    goalId: 10,
    title: '자바스크립트 기초 챕터4 듣기',
    done: true,
    fileUrl: null,
    linkUrl: null,
    dueDate: '2025-04-05',
    createdAt: '2025-03-01',
    updatedAt: '2025-03-01',
    goal: { id: 10, title: '프론트엔드 개발' },
    noteIds: [],
    tags: [],
    favorites: true,
  },
  {
    id: 3,
    teamId: 'team1',
    userId: 1,
    goalId: 20,
    title: '실제 디자인 시스템 사례 조사',
    done: false,
    fileUrl: null,
    linkUrl: null,
    dueDate: '2025-04-15',
    createdAt: '2025-03-02',
    updatedAt: '2025-03-02',
    goal: { id: 20, title: '디자인 스터디' },
    noteIds: [],
    tags: [],
    favorites: true,
  },
  {
    id: 4,
    teamId: 'team1',
    userId: 1,
    goalId: 20,
    title: '로그인/회원가입 폼 만들기',
    done: true,
    fileUrl: null,
    linkUrl: null,
    dueDate: '2025-04-03',
    createdAt: '2025-03-02',
    updatedAt: '2025-03-02',
    goal: { id: 20, title: '디자인 스터디' },
    noteIds: [2],
    tags: [],
    favorites: true,
  },
];
